### ISSUE TITLE
sap_control_function

### ISSUE THREAD

**Issue by herrmie** [sap-linuxlab/community.sap_operations#17]
Hello,

I am facing the problem when executing the sap_control_function: stop_all_sap

![image](https://github.com/sap-linuxlab/community.sap_operations/assets/45813597/720234c2-d7d2-4429-9735-75572b83eb8e)

The Problem seems to be the task in sap_operations/roles/sap_control/tasks/sapcontrol.yml line 20. 
I have commented out the args warn: false:
```yaml
# Execute sapcontrol

- name: SAP {{ sap_control_name_header }} - Executing sapcontrol -nr {{ passed_sap_nr }} -function {{ vars['sap_control_' + funct_type] }}

  ansible.builtin.shell: |

    source ~/.profile && sapcontrol -nr {{ passed_sap_nr }} -function {{ vars['sap_control_' + funct_type] }}

  args:

    executable: /bin/bash

    #warn: false

  become: true

  become_user: "{{ passed_sap_sid | lower }}adm"

  register: sapcontrol_status

  failed_when: "'FAIL' in sapcontrol_status.stdout"
```
