### ISSUE TITLE
sapcontrol stop/start not working

### ISSUE THREAD

**Issue by herrmie** [sap-linuxlab/community.sap_operations#18]
![image](https://github.com/sap-linuxlab/community.sap_operations/assets/45813597/bc3ae5b6-f983-42de-a1fe-796fdee53ceb)

```
---
- name: "sapcontrol" 
  hosts: all
  gather_facts: true
  become: true

  #Function to execute:
  #  restart_all_sap
  #  restart_all_nw
  #  restart_all_hana
  #  restart_sap_nw
  #  restart_sap_hana
  #  stop_all_sap
  #  start_all_sap
  #  stop_all_nw
  #  start_all_nw
  #  stop_all_hana
  #  start_all_hana
  #  stop_sap_nw
  #  start_sap_nw
  #  stop_sap_hana
  #  start_sap_hana

#  vars_prompt:
#    - name: sap_sid
#      prompt: Please enter target SAP System ID (SID)
#      private: no

  vars_prompt:
    - name: sapcontrol_function
      prompt: "Choose valid sap_control_function parameter"
      private: no
  
  vars:
    sap_control_function: "{{ sapcontrol_function }}"

  tasks:

  - name: "Execute {{ sap_control_function }}"
    ansible.builtin.include_role:
      name: { role: community.sap_operations.sap_control }

```
