### ISSUE TITLE
SAP NW Start - wrong starting order. PAS before ASCS

### ISSUE THREAD

**Issue by vsliNQ** [sap-linuxlab/community.sap_operations#30]
Dear community,

we try to start a S4/HANA with the role "community.sap_operations.sap_control ".

We noticed that the PAS is started before the ASCS which leads the Dispatcher to stay in YELLOW status.

Normally the ASCS should start first, and then the PAS.

After a timeout the TASK cancels with an ERROR.

TASK [community.sap_operations.sap_control : SAP NW Start - Executing sapcontrol -nr 01 -function StartWait 180 2] ***************************************************
fatal: [10.0.0.5]: FAILED! => {"changed": true, "cmd": "source ~/.profile && sapcontrol -nr 01 -function StartWait 180 2\n", "delta": "0:03:00.730358", "end": "2024-10-24 10:36:12.309141", "failed_when_result": true, "msg": "non-zero return code", "rc": 2, "start": "2024-10-24 10:33:11.578783", "stderr": "", "stderr_lines": [], "stdout": "\n24.10.2024 10:33:11\nStart\nOK\n\n24.10.2024 10:36:12\nStartWait\nFAIL: Timeout", "stdout_lines": ["", "24.10.2024 10:33:11", "Start", "OK", "", "24.10.2024 10:36:12", "StartWait", "FAIL: Timeout"]}

![image](https://github.com/user-attachments/assets/cfb0ce6d-90b0-4aa1-a58d-30792707c8ce)

![image](https://github.com/user-attachments/assets/94830015-a252-4e7a-a587-d97b97f1f476)

Thanks in advance!

Best regards,
Vasili

**Comment by Jaro-nqc** [comment]
Hi together,

it seems that the tasks to start the systems are executed by the order of the SAP instance numbers. In our case we have these instance numbers:
HANA = 00
PAS = 01
ASCS= 02

In this case first the HANA is started which is fine. But then ansible starts the PAS and this one can't start properly as long as the ASCS is down.

I've swapped the instance numbers of PAS and ASCS to:
ASCS = 01
PAS = 02

After that the start operation works fine :-)

So the current conclusion is that the instances are being started in the order of their instance numbers, which is not a good idea. The start order should depend on the instance type and not on the instance number ... like first start the DB, then start the ASCS, then start the PAS, then start the AAS. The stop operation should use the reverse order ... first stop the AAS, then the PAS, then the ASCS and the DB as last.

Best regards,
Jaro

**Comment by domses** [comment]
a possible quick fix for this would be the following - Insert in prepare.yml before "Sap Control":

- name: SAP Control - Start ASCS first
  vars:
    sap_control_execute_sid: "{{ item.SID }}"
    sap_control_execute_type: "{{ item.Type }}"
    sap_control_execute_instance_nr: "{{ item.NR }}"
    sap_control_execute_instance_type: "{{ item.InstanceType }}"
  ansible.builtin.include_tasks: "sapcontrol.yml"
  loop: "{{ sap_facts_register.ansible_facts.sap }}"
  when:
    - "item.InstanceType | lower == sap_type | lower"
    - funct_type == 'start'
    - item.TYPE == 'ASCS'

**Comment by crweller** [comment]
Hi,
I just faced the same issue on a single VM installation of SAP.
As there might be a number of instances running on the same host/VM I decided to define a sorted list of instances. This list is then used to sort the replied instances from the module sap_system_facts.py.

The new instance list looks like this and goes to the default vars:
```yaml
sap_control_instance_type_sortorder:
  - "HDB"
  - "ERS"
  - "ASCS"
  - "SCS"
  - "PAS"
  - "Java"
  - "WebDisp"
```

Changes to code are only required in the tasks/prepare.yml and will look like this:

![Image](https://github.com/user-attachments/assets/a50f413f-f4fc-40fa-a82f-8639cf54ee71)

The code I have added is the following:

```yaml
- name: Prepare - Sort sap_facts_register by sap_control_instance_type_sortorder
  ansible.builtin.set_fact:
    sorted_sap_facts: "{{ (sorted_sap_facts | default([]) | unique) + (sap_facts_register.ansible_facts.sap | selectattr('TYPE', 'equalto', item) | list | difference(sorted_sap_facts | default([]))) }}"
  loop: "{{ sap_control_instance_type_sortorder | reverse if funct_type == 'stop' else sap_control_instance_type_sortorder }}"
  when: 
    - sap_facts_register.ansible_facts.sap | selectattr('TYPE', 'equalto', item) | list | length > 0
```

When my tests are done, I will contribute my changes to the dev and raise a merge request.

Pls. review and comment.

Thanks,
Rainer
